- input: dota2_stats_v1.pro_players
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.pro_matches
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.rankings
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.heroes
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.hero_stats
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.leagues
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.teams
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.game_mode
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.item_colors
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.lobby_type
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.order_types
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.patch
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.permanent_buffs
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.player_colors
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.skillshots
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.xp_level
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__gold_per_min
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__xp_per_min
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__kills_per_min
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__last_hits_per_min
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__hero_damage_per_min
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__hero_healing_per_min
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.benchmarks__result__tower_damage
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__ranks__rows
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__ranks__fields
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__ranks___parsers
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__mmr__rows
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__mmr__fields
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__mmr___parsers
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__country_mmr__rows
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__country_mmr__fields
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.distribution__country_mmr___parsers
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.hero_stats__roles
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.heroes__roles
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: dota2_stats_v1.rankings__rankings
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
