[project]
name = "cdf"
version = "0.2.0"
description = "A framework to manage data"
authors = [
    {name = "z3z1ma", email = "butler.alex2010@gmail.com"},
]
dependencies = [
    "dlt[duckdb]==0.4.1a1",
    "sqlmesh~=0.58.0",
    "typer[all]>=0.8.0",
    "alive-progress>=3.1.4",
    "harness-featureflags>=1.2.3",
    "python-dotenv>=1.0.0",
    "virtualenv>=20.24.6",
    "duckdb<=0.9.1" # breaking change for sqlmesh in 0.9.2 I think
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "pytest-mock>=3.12.0",
    "scikit-learn"
]

[project.scripts]
cdf = "cdf.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
