[project]
name = "cdf"
version = "0.4.2"
description = "A framework to manage data"
authors = [
    {name = "z3z1ma", email = "butler.alex2010@gmail.com"},
]
dependencies = [
    "dlt[duckdb]>=0.4.1",
    "sqlmesh>=0.62.1",
    "typer[all]>=0.8.0",
    "harness-featureflags>=1.2.3",
    "python-dotenv>=1.0.0",
    "virtualenv>=20.24.6",
    "duckdb<=0.9.1", # breaking change for sqlmesh in 0.9.2 I think
    "pex~=2.1.154",
    "pydantic>=2.5.0,<3.0.0",
    "croniter",
    "psutil",
    "typing-extensions",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "pytest-mock>=3.12.0",
    "scikit-learn"
]

[project.scripts]
cdf = "cdf.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
