[project]
name = "cdf"
version = "0.1.0"
description = "A framework to manage data"
authors = [
    {name = "z3z1ma", email = "butler.alex2010@gmail.com"},
]
dependencies = [
    "dlt[duckdb]~=0.3.22",
    "sqlmesh[duckdb]~=0.46.1",
    "typer[all]>=0.8.0",
    "alive-progress>=3.1.4",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.3",
    "pytest-mock>=3.12.0",
]

[project.scripts]
cdf = "cdf.cli:app"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
