[project]
name = "cdf"
version = "0.4.6"
description = "A framework to manage data continuously"
authors = [
    {name = "z3z1ma", email = "butler.alex2010@gmail.com"},
]
dependencies = [
    "dlt[duckdb]>=0.4.0",
    "sqlmesh>=0.63.0",
    "typer[all]>=0.8.0",
    "harness-featureflags>=1.2.0",
    "python-dotenv>=1.0.0",
    "pex>=2.1.100,<2.2.0",
    "pydantic>=2.5.0,<3.0.0",
    "croniter",
    "psutil",
    "typing-extensions",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "pytest-mock>=3.12.0",
    "scikit-learn"
]

[project.scripts]
cdf = "cdf.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
