- input: us_zip_codes_v1.us_cities
  prefix: 'usa_'
  suffix: ''
  excludes: []
  exclude_patterns:
    - _*
  includes: []
  include_patterns: []
  predicate: '1 = 1'
  computed_columns:
    - case when latitude < 50 then 1 else 0 end as latlessthan50
