[sources.hackernews]
keywords = ["python"]
start_date = "{{ yesterday() }}"
end_date = "{{ today() }}"
daily_load = true

[publishers.httpbin.post]
test_str = "This is a test {{ today() }}"

[transforms]
model_defaults.dialect = "duckdb"

[ff]
provider = "local"


[whatever]
key = {{ 1 + 1}}
