[sources.hackernews]
keywords = ["openai", "altman", "microsoft"]
start_date = "{{ yesterday() }}"
end_date = "{{ today() }}"
daily_load = true

[transforms]
default_gateway = "local"
model_defaults.dialect = "duckdb"

[transforms.gateways.local.connection]
type = "duckdb"
database = "cdf.duckdb"

