[sources.hackernews]
keywords = ["python"]
start_date = "{{ yesterday() }}"
end_date = "{{ today() }}"
daily_load = true

[publishers.httpbin.post]
value = "This is a test {{ today() }}"

[transforms]
default_gateway = "local"
model_defaults.dialect = "duckdb"

[destinations.local]
prod = true
ingest.destination = "duckdb"
ingest.credentials = "duckdb:///cdf.duckdb"
transform.type = "duckdb"
transform.database = "cdf.duckdb"

