- input: hackernews_v1.keyword_hits
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
- input: hackernews_v1.keyword_hits__children
  prefix: ''
  suffix: ''
  excludes: []
  exclude_patterns: []
  includes: []
  include_patterns: []
  predicate: ''
  computed_columns: []
