"""Feature flags for CDF.

NOTE: our primary usage pattern of FF is to get a bunch of flags
for a single component, so we should optimize for that
This means we may not need to pull every possible flag into
the cache. Thus our main entrypoint should be something like
get_flags_for_component(component_id: str, populate_cache_fn=populate_flag_cache)

component_id = <source|transform|publisher>:<name>
flag_name = <component_id>:<flag_name>
"""
import json
import logging
import typing as t
from functools import lru_cache
from pathlib import Path

import dlt
from dlt.sources.helpers import requests
from featureflags.client import CfClient, Config, Target
from featureflags.evaluations.enum import FeatureState  # noqa: F401
from featureflags.evaluations.feature import (
    FeatureConfig,  # noqa: F401
    FeatureConfigKind,
)
from featureflags.interface import Cache
from featureflags.util import log as _ff_logger

import cdf.core.constants as c
from cdf.core.types import Result
from cdf.core.utils import do, search_merge_json

TFlag = t.Union[str, bool, float, t.Dict[str, str]]
TFlags = t.Dict[str, TFlag]

FLAGS: TFlags = {}

Providers = t.Literal["local", "harness", "launchdarkly"]
LazyCfgStr = t.Callable[[], str]


def populate_flag_cache_from_config(
    cache: dict[str, TFlag] | None = None,
    /,
    component_id: str | None = None,
    *,
    with_provider: Providers | None = None,
    **kwargs: t.Any,
) -> TFlags:
    """Populate a cache with flags.

    This function dispatches to the appropriate implementation based on the
    provider specified in the config.
    """
    provider: Providers = with_provider or dlt.config["feature_flags.provider"]
    if provider == "local":
        return populate_flag_cache_from_local(
            cache, component_id=component_id, **kwargs
        )
    elif provider == "harness":
        return populate_flag_cache_from_harness(
            cache, component_id=component_id, **kwargs
        )
    elif provider == "launchdarkly":
        return populate_flag_cache_from_launchdarkly(
            cache, component_id=component_id, **kwargs
        )
    else:
        raise ValueError(
            f"Invalid provider: {provider}, must be one of {t.get_args(Providers)}"
        )


class _Cache(dict, Cache):
    """This exists because the default LRU implementation sucks and does not work with >1000 flags"""

    def set(self, key: str, value: bool) -> None:
        """Set a flag in the cache."""
        self[key] = value

    def remove(self, key) -> None:
        """Remove a flag from the cache."""
        self.pop(key, None)


@lru_cache(maxsize=1)
def _get_harness_client(
    sdk_key: str | LazyCfgStr = lambda: dlt.secrets["feature_flags.harness.sdk_key"],
) -> CfClient:
    """Get a harness client. This is cached so we don't have to create a new client.

    Args:
        sdk_key: The sdk key to use to authenticate with harness.

    Returns:
        The client.
    """
    client = CfClient(
        sdk_key=sdk_key() if callable(sdk_key) else sdk_key,
        config=Config(enable_stream=False, enable_analytics=False, cache=_Cache()),
    )
    client.wait_for_initialization()
    return client


def _harness_identifiers(
    account: bool = True,
    organization: bool = True,
    project: bool = True,
    environment: bool = False,
) -> t.Dict[str, str]:
    """Get the identifiers for the Harness Platform API"""
    identifiers = {}
    if account:
        identifiers["accountIdentifier"] = dlt.config["feature_flags.harness.account"]
    if organization:
        identifiers["orgIdentifier"] = dlt.config["feature_flags.harness.organization"]
    if project:
        identifiers["projectIdentifier"] = dlt.config["feature_flags.harness.project"]
    if environment:
        identifiers["environmentIdentifier"] = dlt.config[
            "feature_flags.harness.environment_id"
        ]
    return identifiers


def _create_harness_flag(
    identifier: str,
    name: str,
    api_key: str | LazyCfgStr = lambda: dlt.secrets["feature_flags.harness.api_key"],
    description: str = "Autogenerated - do not edit",
    kind: FeatureConfigKind = FeatureConfigKind.BOOLEAN,
    variations: t.Optional[t.List[t.Dict[str, str]]] = None,
    **kwargs: t.Any,
) -> Result[dict]:
    """Create a flag in the Harness Platform API

    Args:
        identifier (str): The identifier for the flag
        name (str): The name for the flag
        kind (FeatureConfigKind): The kind of flag
        variations (dict): The variations for the flag
        **kwargs: Additional keyword arguments to pass to the Harness Platform API

    Returns:
        dict: The response from the Harness Platform API

    Raises:
        AssertionError: If the number of variations is less than two
        requests.exceptions.HTTPError: If the response from the Harness Platform API
            is not successful
    """
    if variations is None:
        variations = [
            {
                "identifier": "on-variation",
                "value": "true",
            },
            {
                "identifier": "off-variation",
                "value": "false",
            },
        ]
    assert len(variations) >= 2, "Must have at least two variations"
    resp = requests.post(
        "https://app.harness.io/gateway/cf/admin/features",
        params=_harness_identifiers(project=False),
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key() if callable(api_key) else api_key,
        },
        json={
            "defaultOnVariation": variations[0]["identifier"],
            "defaultOffVariation": variations[1]["identifier"],
            "description": description,
            "identifier": identifier,
            "name": name,
            "kind": kind.value,
            "permanent": True,
            "project": dlt.config["feature_flags.harness.project"],
            "variations": variations,
            **kwargs,
        },
    )
    if resp.ok:
        return Result(resp.json(), None)
    return Result(None, Exception(resp.text))


@lru_cache(maxsize=1)
def _get_harness_flag(
    flag_id: str,
    api_key: str | LazyCfgStr = lambda: dlt.secrets["feature_flags.harness.api_key"],
) -> Result[dict]:
    """Get a flag from the Harness Platform API

    Args:
        flag_id (str): The flag identifier

    Returns:
        dict: The flag

    Raises:
        requests.exceptions.HTTPError: If the request fails
    """
    resp = requests.get(
        f"https://app.harness.io/gateway/cf/admin/features/{flag_id}",
        headers={"x-api-key": api_key() if callable(api_key) else api_key},
        params={**_harness_identifiers(environment=True), "metrics": False},
    )
    if resp.ok:
        return Result(resp.json(), None)
    return Result(None, Exception(resp.text))


def _harness_flag_exists(flag_id: str, ff_client: CfClient) -> bool:
    """Check if a flag exists in the Harness Platform API

    We make this fast by checking the SDK cache.

    Args:
        flag_id (str): The identifier for the flag

    Returns:
        bool: True if the flag exists, False otherwise
    """
    try:
        return f"flags/{flag_id}" in list(ff_client._repository.cache.keys()) or bool(
            Result.apply(_get_harness_flag, flag_id)
        )
    except requests.HTTPError as e:
        if e.response and e.response.status_code in (404, 400):
            return False
        raise


def _harness_id_to_component_id(harness_id: str) -> str:
    """Convert a Harness Platform API flag id to a component id

    Args:
        harness_id (str): The Harness Platform API flag id

    Returns:
        str: The component id
    """
    if harness_id.upper().startswith("FLAGS/"):
        harness_id = harness_id.split("/", 1)[1]
    return harness_id.replace("__", ":", 1)


def _component_id_to_harness_id(component_id: str) -> str:
    """Convert a component id to a Harness Platform API flag id

    Args:
        component_id (str): The component id

    Returns:
        str: The Harness Platform API flag id
    """
    return "__".join(component_id.split(":")[1:])


def populate_flag_cache_from_harness(
    cache: dict[str, TFlag] | None = None,
    /,
    component_id: str | None = None,
    account: str | LazyCfgStr = lambda: dlt.config["feature_flags.harness.account"],
    project: str | LazyCfgStr = lambda: dlt.config["feature_flags.harness.project"],
    organization: str
    | LazyCfgStr = lambda: dlt.config["feature_flags.harness.organization"],
    sdk_key: str | LazyCfgStr = lambda: dlt.secrets["feature_flags.harness.sdk_key"],
    api_key: str | LazyCfgStr = lambda: dlt.secrets["feature_flags.harness.api_key"],
) -> TFlags:
    """Populate a cache with flags.

    Args:
        cache: A cache to populate.
        component_id: The id of the component to search for flags. Used to reduce the
            number of fetched flags. Additionally, if a flag for the given component id
            does not exist, we will create it.
        sdk_key: The sdk key to use to authenticate with harness.

    Returns:
        dict: The populated cache.
    """
    _ff_logger.setLevel(logging.ERROR)
    cache = cache if cache is not None else {}
    ff_client = _get_harness_client(sdk_key() if callable(sdk_key) else sdk_key)
    account, project, organization = (
        account() if callable(account) else account,
        project() if callable(project) else project,
        organization() if callable(organization) else organization,
    )
    if component_id:
        harness_safeident = _component_id_to_harness_id(component_id)
        exists = _harness_flag_exists(harness_safeident, ff_client)
        if not exists:
            _create_harness_flag(
                harness_safeident,
                f"Extract {' '.join(component_id.split(':')[1:]).title()}",
                api_key=api_key,
            )
            cache[component_id] = False
        else:
            rv = ff_client.bool_variation(harness_safeident, Target("cdf"), False)
            cache[component_id] = rv
    else:
        cache.update(
            {
                _harness_id_to_component_id(k): ff_client._repository.cache.get(k)
                for k in ff_client._repository.cache.keys()
            }
        )
    return cache


def populate_flag_cache_from_launchdarkly(
    cache: dict[str, TFlag] | None = None,
    /,
    component_id: str | None = None,
    account: str | None = None,
    api_key: str | None = None,
) -> TFlags:
    raise NotImplementedError


def populate_flag_cache_from_local(
    cache: dict[str, TFlag] | None = None,
    /,
    component_id: str | None = None,
    component_paths: t.Iterable[str | Path] | None = None,
    max_depth: int = 3,
) -> TFlags:
    """Populate a cache with flags.

    Args:
        cache: A cache to populate.
        component_id: The id of the component to search for flags. Used to filter the cache.
            This is not used for the local implementation but is a required parameter for
            the interface.
        component_paths: A list of paths to search for flags. Supplied via closure.

    Returns:
        dict: The populated cache.
    """
    _ = component_id  # This is cheap, we don't need the id
    cache = cache if cache is not None else {}
    component_paths = component_paths or [Path.home() / ".cdf"] + c.COMPONENT_PATHS
    for raw_path in component_paths:
        path = Path(raw_path).expanduser().resolve()
        search_parent_dirs = path != Path.home()
        if search_parent_dirs:
            do(
                cache.update,
                map(lambda f: search_merge_json(path, f, max_depth), c.CDF_FLAG_FILES),
            )
        else:
            do(
                cache.update,
                map(
                    lambda f: json.loads((path / f).read_text()),
                    filter(lambda f: (path / f).exists(), c.CDF_FLAG_FILES),
                ),
            )
    return cache


def get_flags_for_component(
    component_id: str,
    populate_cache_fn: t.Callable[
        [TFlags, str], TFlags
    ] = populate_flag_cache_from_config,
) -> TFlags:
    """Get flags for a specific component id populating the cache if needed.

    Args:
        component_id: The component to find. In the form of <source|transform|publisher>:<name>
        populate_cache_fn: A function which takes a cache dict and component id and populates
            the cache. The implementer can make decisions on how to interface with the network
            given the supplied component id which is a prefix for the requested flags. The
            implementer should also decide what to do if the component_id is not found in the
            cache. Typically this means creating a flag in the feature flag provider.

    Returns:
        dict: The subset of flags related to the component, empty dict if no flags found
    """
    if not FLAGS or not any(k.startswith(component_id) for k in FLAGS):
        populate_cache_fn(FLAGS, component_id)
    subset = {k: v for k, v in FLAGS.items() if k.startswith(component_id)}
    return subset
